name: w_cupertino_date_picker
description: w_cupertino_date_picker which belongs to uic group now ))
version: 3.0.0
homepage: https://github.com/AbuAbdulloh/w_cupertino_date_picker.git

dependencies:
  flutter:
    sdk: flutter

flutter:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=0.4.1"
